# Site settings
title: Jonathan Hui blog
email: 
description: “Software architect”
baseurl: ""
url: "http://jhui.github.io"
github_username:  jhui

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap